backend:
  name: git-gateway
  branch: main

media_folder: "assets/img/uploads"  # Where images are stored
public_folder: "/assets/img/uploads"

collections:
  - name: "news"
    label: "News Posts"
    folder: "_posts/news"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "image", label: "Featured Image", widget: "image" }
      - { name: "excerpt", label: "Short Description", widget: "text" }
      - { name: "body", label: "Content", widget: "markdown" }